videojuego(minecraft,sandbox).
videojuego(valorant,shooter).
videojuego(fifa25,deportes).
videojuego(gta5,accion).
videojuego(the_witcher_3,rpg).
videojuego(cyberpunk_2077,rpg).
videojuego(elden_ring,rpg).
videojuego(counter_strike_2,shooter).
videojuego(red_dead_redemption_2,aventura).
videojuego(god_of_war_ragnarok,accion).
videojuego(hollow_knight,metroidvania).
videojuego(terraria,sandbox).

plataforma(minecraft,pc).
plataforma(valorant,pc).
plataforma(fifa25,playstation).
plataforma(gta5,pc).
plataforma(the_witcher_3,pc).
plataforma(cyberpunk_2077,pc).
plataforma(elden_ring,pc).
plataforma(counter_strike_2,pc).
plataforma(red_dead_redemption_2,pc).
plataforma(god_of_war_ragnarok,playstation).
plataforma(hollow_knight,pc).
plataforma(terraria,pc).

desarrolladora(minecraft,mojang).
desarrolladora(valorant,riot_games).
desarrolladora(fifa25,ea_sports).
desarrolladora(gta5,rockstar_games).
desarrolladora(the_witcher_3,cd_projekt_red).
desarrolladora(cyberpunk_2077,cd_projekt_red).
desarrolladora(elden_ring,fromsoftware).
desarrolladora(counter_strike_2,valve).
desarrolladora(red_dead_redemption_2,rockstar_games).
desarrolladora(god_of_war_ragnarok,santa_monica_studio).
desarrolladora(hollow_knight,team_cherry).
desarrolladora(terraria,re_logic).